[[positions]]
id = "EPWW_B_CTR"
prefixes = ["EPWW"]
frequency = "127.025"
facility_type = "CTR"

[[positions]]
id = "EPWW_CTR"
prefixes = ["EPWW"]
frequency = "125.450"
facility_type = "CTR"

[[positions]]
id = "EPWW_C_CTR"
prefixes = ["EPWW"]
frequency = "133.475"
facility_type = "CTR"

[[positions]]
id = "EPWW_D_CTR"
prefixes = ["EPWW"]
frequency = "134.225"
facility_type = "CTR"

[[positions]]
id = "EPWW_E_CTR"
prefixes = ["EPWW"]
frequency = "120.950"
facility_type = "CTR"

[[positions]]
id = "EPWW_F_CTR"
prefixes = ["EPWW"]
frequency = "129.075"
facility_type = "CTR"

[[positions]]
id = "EPWW_G_CTR"
prefixes = ["EPWW"]
frequency = "124.925"
facility_type = "CTR"

[[positions]]
id = "EPWW_I_CTR"
prefixes = ["EPWW"]
frequency = "134.875"
facility_type = "CTR"

[[positions]]
id = "EPWW_J_CTR"
prefixes = ["EPWW"]
frequency = "124.625"
facility_type = "CTR"

[[positions]]
id = "EPWW_N_CTR"
prefixes = ["EPWW"]
frequency = "132.700"
facility_type = "CTR"

[[positions]]
id = "EPWW_R_CTR"
prefixes = ["EPWW"]
frequency = "123.625"
facility_type = "CTR"

[[positions]]
id = "EPWW_U_CTR"
prefixes = ["EPWW"]
frequency = "130.625"
facility_type = "CTR"

[[positions]]
id = "EPDE_APP"
prefixes = ["EPDE"]
frequency = "128.250"
facility_type = "APP"

[[positions]]
id = "EPGD_APP"
prefixes = ["EPGD"]
frequency = "127.280"
facility_type = "APP"

[[positions]]
id = "EPGD_I_APP"
prefixes = ["EPGD"]
frequency = "127.150"
facility_type = "APP"

[[positions]]
id = "EPGD_L_APP"
prefixes = ["EPGD"]
frequency = "133.660"
facility_type = "APP"

[[positions]]
id = "EPKK_APP"
prefixes = ["EPKK"]
frequency = "121.075"
facility_type = "APP"

[[positions]]
id = "EPKK_E_APP"
prefixes = ["EPKK"]
frequency = "126.975"
facility_type = "APP"

[[positions]]
id = "EPKK_I_APP"
prefixes = ["EPKK"]
frequency = "119.275"
facility_type = "APP"

[[positions]]
id = "EPKK_KK_APP"
prefixes = ["EPKK"]
frequency = "126.530"
facility_type = "APP"

[[positions]]
id = "EPKK_KT_APP"
prefixes = ["EPKK"]
frequency = "135.405"
facility_type = "APP"

[[positions]]
id = "EPKK_RZ_APP"
prefixes = ["EPKK"]
frequency = "133.030"
facility_type = "APP"

[[positions]]
id = "EPKS_P_APP"
prefixes = ["EPKS"]
frequency = "120.750"
facility_type = "APP"

[[positions]]
id = "EPPO_I_APP"
prefixes = ["EPPO"]
frequency = "126.300"
facility_type = "APP"

[[positions]]
id = "EPPO_N_APP"
prefixes = ["EPPO"]
frequency = "128.925"
facility_type = "APP"

[[positions]]
id = "EPPO_S_APP"
prefixes = ["EPPO"]
frequency = "123.040"
facility_type = "APP"

[[positions]]
id = "EPSY_I_APP"
prefixes = ["EPSY"]
frequency = "118.775"
facility_type = "APP"

[[positions]]
id = "EPWA_APP"
prefixes = ["EPWA"]
frequency = "128.805"
facility_type = "APP"

[[positions]]
id = "EPWA_F_APP"
prefixes = ["EPWA"]
frequency = "129.380"
facility_type = "APP"

[[positions]]
id = "EPWA_I_APP"
prefixes = ["EPWA"]
frequency = "119.450"
facility_type = "APP"

[[positions]]
id = "EPWA_N_APP"
prefixes = ["EPWA"]
frequency = "125.055"
facility_type = "APP"

[[positions]]
id = "EPWA_S_APP"
prefixes = ["EPWA"]
frequency = "135.930"
facility_type = "APP"

[[positions]]
id = "EPBA_R_TWR"
prefixes = ["EPBA"]
frequency = "118.330"
facility_type = "TWR"

[[positions]]
id = "EPBC_I_TWR"
prefixes = ["EPBC"]
frequency = "119.180"
facility_type = "TWR"

[[positions]]
id = "EPBK_R_TWR"
prefixes = ["EPBK"]
frequency = "123.205"
facility_type = "TWR"

[[positions]]
id = "EPBY_TWR"
prefixes = ["EPBY"]
frequency = "131.005"
facility_type = "TWR"

[[positions]]
id = "EPDE_TWR"
prefixes = ["EPDE"]
frequency = "122.750"
facility_type = "TWR"

[[positions]]
id = "EPGD_TWR"
prefixes = ["EPGD"]
frequency = "118.105"
facility_type = "TWR"

[[positions]]
id = "EPGL_R_TWR"
prefixes = ["EPGL"]
frequency = "118.260"
facility_type = "TWR"

[[positions]]
id = "EPGY_R_TWR"
prefixes = ["EPGY"]
frequency = "126.855"
facility_type = "TWR"

[[positions]]
id = "EPJA_R_TWR"
prefixes = ["EPJA"]
frequency = "122.830"
facility_type = "TWR"

[[positions]]
id = "EPKA_R_TWR"
prefixes = ["EPKA"]
frequency = "118.080"
facility_type = "TWR"

[[positions]]
id = "EPKI_R_TWR"
prefixes = ["EPKI"]
frequency = "119.405"
facility_type = "TWR"

[[positions]]
id = "EPKK_TWR"
prefixes = ["EPKK"]
frequency = "123.255"
facility_type = "TWR"

[[positions]]
id = "EPKM_R_TWR"
prefixes = ["EPKM"]
frequency = "120.080"
facility_type = "TWR"

[[positions]]
id = "EPKP_R_TWR"
prefixes = ["EPKP"]
frequency = "118.605"
facility_type = "TWR"

[[positions]]
id = "EPKR_R_TWR"
prefixes = ["EPKR"]
frequency = "119.555"
facility_type = "TWR"

[[positions]]
id = "EPKS_TWR"
prefixes = ["EPKS"]
frequency = "121.025"
facility_type = "TWR"

[[positions]]
id = "EPKT_TWR"
prefixes = ["EPKT"]
frequency = "129.255"
facility_type = "TWR"

[[positions]]
id = "EPLB_TWR"
prefixes = ["EPLB"]
frequency = "136.430"
facility_type = "TWR"

[[positions]]
id = "EPLL_TWR"
prefixes = ["EPLL"]
frequency = "124.230"
facility_type = "TWR"

[[positions]]
id = "EPLR_R_TWR"
prefixes = ["EPLR"]
frequency = "121.390"
facility_type = "TWR"

[[positions]]
id = "EPML_I_TWR"
prefixes = ["EPML"]
frequency = "119.105"
facility_type = "TWR"

[[positions]]
id = "EPMO_TWR"
prefixes = ["EPMO"]
frequency = "123.930"
facility_type = "TWR"

[[positions]]
id = "EPNT_R_TWR"
prefixes = ["EPNT"]
frequency = "122.305"
facility_type = "TWR"

[[positions]]
id = "EPOD_R_TWR"
prefixes = ["EPOD"]
frequency = "124.480"
facility_type = "TWR"

[[positions]]
id = "EPPO_TWR"
prefixes = ["EPPO"]
frequency = "119.980"
facility_type = "TWR"

[[positions]]
id = "EPPZ_R_TWR"
prefixes = ["EPPZ"]
frequency = "122.600"
facility_type = "TWR"

[[positions]]
id = "EPRA_TWR"
prefixes = ["EPRA"]
frequency = "118.430"
facility_type = "TWR"

[[positions]]
id = "EPRZ_TWR"
prefixes = ["EPRZ"]
frequency = "126.805"
facility_type = "TWR"

[[positions]]
id = "EPSC_TWR"
prefixes = ["EPSC"]
frequency = "121.255"
facility_type = "TWR"

[[positions]]
id = "EPSY_TWR"
prefixes = ["EPSY"]
frequency = "118.030"
facility_type = "TWR"

[[positions]]
id = "EPWA_TWR"
prefixes = ["EPWA"]
frequency = "118.305"
facility_type = "TWR"

[[positions]]
id = "EPWR_TWR"
prefixes = ["EPWR"]
frequency = "120.255"
facility_type = "TWR"

[[positions]]
id = "EPZG_TWR"
prefixes = ["EPZG"]
frequency = "118.755"
facility_type = "TWR"

[[positions]]
id = "EPZP_R_TWR"
prefixes = ["EPZP"]
frequency = "130.780"
facility_type = "TWR"

[[positions]]
id = "EPZR_R_TWR"
prefixes = ["EPZR"]
frequency = "122.805"
facility_type = "TWR"

[[positions]]
id = "EPGD_GND"
prefixes = ["EPGD"]
frequency = "131.330"
facility_type = "GND"

[[positions]]
id = "EPKK_GND"
prefixes = ["EPKK"]
frequency = "118.105"
facility_type = "GND"

[[positions]]
id = "EPKT_GND"
prefixes = ["EPKT"]
frequency = "121.805"
facility_type = "GND"

[[positions]]
id = "EPPO_GND"
prefixes = ["EPPO"]
frequency = "124.140"
facility_type = "GND"

[[positions]]
id = "EPRA_M_GND"
prefixes = ["EPRA"]
frequency = "121.750"
facility_type = "GND"

[[positions]]
id = "EPRZ_GND"
prefixes = ["EPRZ"]
frequency = "121.805"
facility_type = "GND"

[[positions]]
id = "EPWA_GND"
prefixes = ["EPWA"]
frequency = "121.905"
facility_type = "GND"

[[positions]]
id = "EPWR_GND"
prefixes = ["EPWR"]
frequency = "121.805"
facility_type = "GND"

[[positions]]
id = "EPKK_DEL"
prefixes = ["EPKK"]
frequency = "121.980"
facility_type = "DEL"

[[positions]]
id = "EPKT_DEL"
prefixes = ["EPKT"]
frequency = "124.080"
facility_type = "DEL"

[[positions]]
id = "EPLL_DEL"
prefixes = ["EPLL"]
frequency = "120.005"
facility_type = "DEL"

[[positions]]
id = "EPMO_DEL"
prefixes = ["EPMO"]
frequency = "119.680"
facility_type = "DEL"

[[positions]]
id = "EPPO_DEL"
prefixes = ["EPPO"]
frequency = "121.805"
facility_type = "DEL"

[[positions]]
id = "EPWA_DEL"
prefixes = ["EPWA"]
frequency = "121.605"
facility_type = "DEL"

[[positions]]
id = "EPWR_DEL"
prefixes = ["EPWR"]
frequency = "124.565"
facility_type = "DEL"
